### PR TITLE
add httparty to gem dependency because it is require to use the gem

### PR DESCRIPTION
**Pull request by earlonrails**
require 'stubhub'
LoadError: cannot load such file -- httparty

### CODE REVIEW

**Comment by biznickman** [comment]
Why hasn't this been merged?

**Comment by rloomba** [comment]
@biznickman good question. I'll merge it now.

Stubhub has recently change/limited/restricted their API's, so no guarantees that this library works.

**Comment by chooserich** [comment]
@rloomba Ah yeah it's not working. Do you know when they did that? Is it now only manually accepted partners or something?

**Comment by rloomba** [comment]
@biznickman 😞 yeah, I think it happened ~ a year or so ago. Yep, you have to contact them for details.

**Pull request merged**
